name: Publish packages

on:
  push:
    tags: ["*"]

env:
  # XXX(zk): tree-sitter 0.25 was only recently released, bringing ABI 15
  #          with it. However, py-tree-sitter still only supports up to 14,
  #          and the Python bindings are my main concern here.
  TREE_SITTER_ABI_VERSION: "14"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  github:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      generate: true
      attestations: true
  pypi:
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@main
    with:
      generate: true
    env:
      TREE_SITTER_ABI_VERSION: ${{ env.TREE_SITTER_ABI_VERSION }}
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
